# Generated by Django 4.2.5 on 2023-10-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0002_alter_courses_options_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
    ]
